// SOLDIER(company,co,)
// SOLDIER(company,xo, )
// SOLDIER(company,mio )
// SOLDIER(company,colo )
// SOLDIER(company,fo )

SOLDIER(platoon,pl,o_officer_f)
SOLDIER(platoon,psgt,o_t_officer_f)
SOLDIER(platoon,uav,o_soldier_uav_f)
SOLDIER(platoon,jtac,o_recon_jtac_f)
SOLDIER(platoon,medic,o_t_medic_f)

SOLDIER(squad,sl,o_soldier_sl_f)
SOLDIER(squad,ftl,o_soldier_tl_f)
SOLDIER(squad,ar,o_soldier_ar_f)
SOLDIER(squad,gl,o_soldier_gl_f)
SOLDIER(squad,gl2,o_t_soldier_gl_f)
SOLDIER(squad,light,o_soldier_lite_f)
SOLDIER(squad,aar,o_soldier_f)
SOLDIER(squad,lat,o_soldier_lat_f)
SOLDIER(squad,cm,o_medic_f)
SOLDIER(squad,dm,o_soldier_m_f)
SOLDIER(squad,eng,o_engineer_f)

SOLDIER(weapons,mg,o_heavygunner_f)
SOLDIER(weapons,amg,o_soldier_aar)
SOLDIER(weapons,hmg,o_support_mg_f)
SOLDIER(weapons,ahmg,o_support_amg_f)
SOLDIER(weapons,gmg,o_support_gmg_f)
SOLDIER(weapons,agmg,o_t_support_amg_f)
SOLDIER(weapons,atgm,o_soldier_at_f)
SOLDIER(weapons,aatgm,o_soldier_aat_f)
SOLDIER(weapons,aa,o_soldier_aa_f)
SOLDIER(weapons,aaa,o_soldier_aaa_f)
SOLDIER(weapons,mort,o_support_mort_f)
SOLDIER(weapons,amort,o_support_amort_f)
SOLDIER(weapons,acmort,o_soldier_a_f)

SOLDIER(recon,rm,o_recon_f)
SOLDIER(recon,tl,o_recon_tl_f)
SOLDIER(recon,ar,o_pathfinder_f)
SOLDIER(recon,gl,o_t_recon_f)
SOLDIER(recon,lat,o_recon_lat_f)
SOLDIER(recon,cm,o_recon_medic_f)
SOLDIER(recon,dm,o_recon_m_f)
SOLDIER(recon,exp,o_recon_exp_f)

SOLDIER(diver,rm,o_diver_f)
SOLDIER(diver,tl,o_diver_tl_f)
SOLDIER(diver,exp,o_diver_exp_f)
SOLDIER(diver,cm,o_t_diver_f)
SOLDIER(diver,dm,o_t_diver_exp_f)
SOLDIER(diver,jtac,o_t_diver_tl_f)

SOLDIER(sniper,spot,o_spotter_f)
SOLDIER(sniper,ap,o_ghillie_ard_f)
SOLDIER(sniper,am,o_ghillie_lsh_f)
SOLDIER(sniper,exp,o_sniper_f)

SOLDIER(crew,common,o_crew_f)
SOLDIER(crew,cmd,o_t_crew_f)
SOLDIER(crew,jet,o_pilot_f)
SOLDIER(crew,heli,o_helicrew_f)
SOLDIER(crew,helipilot,o_helipilot_f)

SOLDIER(logistics,common,o_soldier_repair_f)

//SOLDIER(medevac,doc, )
//SOLDIER(medevac,tl, )
//SOLDIER(medevac,heli, )
//SOLDIER(medevac,drv, )
