// SOLDIER(company,co,)
// SOLDIER(company,xo, )
// SOLDIER(company,mio )
// SOLDIER(company,colo )
// SOLDIER(company,fo )

SOLDIER(platoon,pl,i_officer_f)
// SOLDIER(platoon,psgt,i_t_officer_f)
SOLDIER(platoon,uav,i_soldier_uav_f)
// SOLDIER(platoon,jtac,i_recon_jtac_f)
// SOLDIER(platoon,medic,i_t_medic_f)

SOLDIER(squad,sl,i_soldier_sl_f)
SOLDIER(squad,ftl,i_soldier_tl_f)
SOLDIER(squad,ar,i_soldier_ar_f)
SOLDIER(squad,gl,i_soldier_gl_f)
// SOLDIER(squad,gl2,i_t_soldier_gl_f)
SOLDIER(squad,light,i_soldier_lite_f)
SOLDIER(squad,aar,i_soldier_f)
SOLDIER(squad,lat,i_soldier_lat_f)
SOLDIER(squad,cm,i_medic_f)
SOLDIER(squad,dm,i_soldier_m_f)
SOLDIER(squad,eng,i_engineer_f)

// SOLDIER(weapons,mg,i_heavygunner_f)
// SOLDIER(weapons,amg,i_soldier_aar)
SOLDIER(weapons,hmg,i_support_mg_f)
SOLDIER(weapons,ahmg,i_support_amg_f)
SOLDIER(weapons,gmg,i_support_gmg_f)
SOLDIER(weapons,agmg,i_t_support_amg_f)
SOLDIER(weapons,atgm,i_soldier_at_f)
SOLDIER(weapons,aatgm,i_soldier_aat_f)
SOLDIER(weapons,aa,i_soldier_aa_f)
SOLDIER(weapons,aaa,i_soldier_aaa_f)
SOLDIER(weapons,mort,i_support_mort_f)
SOLDIER(weapons,amort,i_support_amort_f)
SOLDIER(weapons,acmort,i_soldier_a_f)

// SOLDIER(recon,rm,i_recon_f)
// SOLDIER(recon,tl,i_recon_tl_f)
// SOLDIER(recon,ar,i_recon_sharpshooter_f)
// SOLDIER(recon,gl,i_t_recon_f)
// SOLDIER(recon,lat,i_recon_lat_f)
// SOLDIER(recon,cm,i_recon_medic_f)
// SOLDIER(recon,dm,i_recon_m_f)
// SOLDIER(recon,exp,i_recon_exp_f)

SOLDIER(diver,rm,i_diver_f)
SOLDIER(diver,tl,i_diver_tl_f)
SOLDIER(diver,exp,i_diver_exp_f)
// SOLDIER(diver,cm,i_t_diver_f)
// SOLDIER(diver,dm,i_t_diver_exp_f)
// SOLDIER(diver,jtac,i_t_diver_tl_f)

SOLDIER(sniper,spot,i_spotter_f)
SOLDIER(sniper,ap,i_ghillie_ard_f)
SOLDIER(sniper,am,i_ghillie_lsh_f)
SOLDIER(sniper,exp,i_sniper_f)

SOLDIER(crew,common,i_crew_f)
// SOLDIER(crew,cmd,i_t_crew_f)
SOLDIER(crew,jet,i_pilot_f)
SOLDIER(crew,heli,i_helicrew_f)
SOLDIER(crew,helipilot,i_helipilot_f)

SOLDIER(logistics,common,i_soldier_repair_f)

//SOLDIER(medevac,doc, )
//SOLDIER(medevac,tl, )
//SOLDIER(medevac,heli, )
//SOLDIER(medevac,drv, )
